# http://travis-ci.org/#!/jupyter/jupyterhub
language: python
sudo: false
python:
    - 3.6-dev
    - 3.5
    - 3.4
    - 3.3
before_install:
    - npm install
    - npm install -g configurable-http-proxy
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install --pre -f travis-wheels/wheelhouse -r dev-requirements.txt .
script:
    - travis_retry py.test --cov=jupyterhub -v
after_success:
    - codecov
matrix:
  include:
    - python: 3.5
      env: JUPYTERHUB_TEST_SUBDOMAIN_HOST=http://127.0.0.1.xip.io:8000
