name: jhub_docs
channels:
  - conda-forge
  - defaults
dependencies:
- nodejs
- python=3
- jinja2
- pamela
- requests
- sqlalchemy>=1
- tornado>=4.1
- traitlets>=4.1
- sphinx_rtd_theme
- pip:
    - recommonmark
    - sphinx==1.5a1
