name: jhub_docs
channels:
  - conda-forge
dependencies:
- pyyaml
- nodejs
- python=3.5
- jinja2
- pamela
- requests
- sqlalchemy>=1
- tornado>=4.1
- traitlets>=4.1
- sphinx>=1.3.6
- sphinx_rtd_theme
- pip:
    - pyyaml
    - readthedocs-build
    - readthedocs.doc_builder.config
    - recommonmark==0.4.0
