name: jhub_docs
channels:
  - conda-forge
dependencies:
- nodejs
- python=3.5
- alembic
- jinja2
- pamela
- requests
- sqlalchemy>=1
- tornado>=4.1
- traitlets>=4.1
- sphinx>=1.4, !=1.5.4
- sphinx_rtd_theme
- pip:
  - jupyter_alabaster_theme
  - python-oauth2
  - recommonmark==0.4.0
